### ISSUE TITLE
Some important dangling licensing requirements

### ISSUE THREAD

**Issue by riverar** [mrlacey/TemplateStudio#2]
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
https://github.com/microsoft/WindowsTemplateStudio/blob/dev/LICENSE.md

**Comment by mrlacey** [comment]
Thanks. On it.

**Comment by mrlacey** [comment]
The license has been added in this repo and is now also included (along with all other 3rd party licenses) when installing the extension.
