### ISSUE TITLE
Suggestion: Support for multi-platform frameworks

### ISSUE THREAD

**Issue by Luk164** [mrlacey/TemplateStudio#5]
I would like to suggest adding support for using multi-platform frameworks like Uno or Avalonia. These already have some support for UWP, WPF and WinUI, so they could be used as a sort of base layer, resulting in the generated templates gaining all the advantages they carry. 

I think being able to quickly generate a powerful template than runs on many platforms would be useful to a wide array of developers.

**Comment by mrlacey** [comment]
It's on my [radar](https://twitter.com/mrlacey/status/1424040177819922436/photo/1) 😉

**Comment by mrlacey** [comment]
This is covered by https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.MauiAppAccelerator
